name: CI Bench

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Run Bench
        run: yarn bench
